version: '3'
services:
    web:
        container_name: swdb-server
        image: nginx:latest
        ports:
            - "8888:80"
        volumes:
            - ./.docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
            - ./:/var/www/html
        depends_on:
            - php
        restart: always
    php:
        container_name: swdb-php
        build:
            context: .
        volumes:
            - ./.docker/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
            - ./:/var/www/html:rw
        restart: always
volumes:
    sleekwaredb-api: {}
